DROP TABLE LECTURE_TBL;
DROP TABLE ENROLL_TBL;
DROP TABLE COURSE_TBL;
DROP TABLE STUDENT_TBL;
DROP TABLE PROFESSOR_TBL;
CREATE TABLE PROFESSOR_TBL(
    PRO_NO          NUMBER              NOT NULL,
    PRO_NAME        VARCHAR2(15 BYTE)   NOT NULL,
    PRO_MAJOR       VARCHAR2(15 BYTE)   NOT NULL,
    CONSTRAINT PRO_PK       PRIMARY KEY(PRO_NO)
);
CREATE TABLE STUDENT_TBL(
    STD_NO          NUMBER              NOT NULL,
    STD_NAME        VARCHAR2(15 BYTE)   NOT NULL,
    STD_ADDRESS     VARCHAR2(100 BYTE)  NULL,
    STD_GRADE       NUMBER              NOT NULL,
    PRO_NO          NUMBER              NULL,
    CONSTRAINT STD_PK       PRIMARY KEY(STD_NO),
    CONSTRAINT PRO_STD_FK   FOREIGN KEY(PRO_NO) REFERENCES PROFESSOR_TBL(PRO_NO) 
    ON DELETE SET NULL
);

CREATE TABLE COURSE_TBL(
    COU_NO          NUMBER              NOT NULL,
    COU_SUBNAME     VARCHAR(15 BYTE)    NOT NULL,
    COU_SCORE       NUMBER(4,1)            NOT NULL,
    CONSTRAINT COU_PK       PRIMARY KEY(COU_NO)
);
CREATE TABLE ENROLL_TBL(
    ENR_NO          NUMBER              NOT NULL,
    STD_NO          NUMBER              NOT NULL,
    COU_NO          NUMBER              NOT NULL,
    ENR_DATE        DATE                NOT NULL,
    CONSTRAINT ENR_PK       PRIMARY KEY(ENR_NO),
    CONSTRAINT STD_ENR_FK   FOREIGN KEY(STD_NO)    REFERENCES STUDENT_TBL(STD_NO)
    ON DELETE CASCADE,
    CONSTRAINT COU_ENR_FK   FOREIGN KEY(COU_NO)    REFERENCES COURSE_TBL(COU_NO)
    ON DELETE CASCADE
);


CREATE TABLE LECTURE_TBL(
    LEC_NO          NUMBER              NOT NULL,
    PRO_NO          NUMBER              NOT NULL,
    ENR_NO          NUMBER              NOT NULL,
    LEC_NAME        VARCHAR(20 BYTE)    NOT NULL,
    LEC_CLASS       CHAR   (3 BYTE)     NOT NULL,
    CONSTRAINT LEC_PK       PRIMARY KEY(LEC_NO),
    CONSTRAINT PRO_LEC_FK   FOREIGN KEY(PRO_NO)     REFERENCES PROFESSOR_TBL(PRO_NO)
    ON DELETE CASCADE,
    CONSTRAINT ENR_LEC_FK   FOREIGN KEY(ENR_NO)     REFERENCES ENROLL_TBL(ENR_NO) 
    ON DELETE CASCADE
);

DROP SEQUENCE PRO_SEQ;
CREATE SEQUENCE PRO_SEQ ORDER;

INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_MAJOR) VALUES(PRO_SEQ.NEXTVAL, '김길태', '수학');
INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_MAJOR) VALUES(PRO_SEQ.NEXTVAL, '이상호', '국어');
INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_MAJOR) VALUES(PRO_SEQ.NEXTVAL, '오일남', '영어');


INSERT INTO STUDENT_TBL(STD_NO, STD_NAME, STD_ADDRESS, STD_GRADE,PRO_NO) VALUES(21001, '홍길동', '서울', 1,  3);
INSERT INTO STUDENT_TBL(STD_NO, STD_NAME, STD_ADDRESS, STD_GRADE,PRO_NO) VALUES(21003, '이영선', '인천', 2,  2);
INSERT INTO STUDENT_TBL(STD_NO, STD_NAME, STD_ADDRESS, STD_GRADE,PRO_NO) VALUES(22004, '삼국지', '울산', 3,  3);

DROP SEQUENCE COU_SEQ;
CREATE SEQUENCE COU_SEQ 
START WITH 21 
ORDER;


INSERT INTO COURSE_TBL(COU_NO, COU_SUBNAME,COU_SCORE) VALUES(COU_SEQ.NEXTVAL, '수학', 4.5);
INSERT INTO COURSE_TBL(COU_NO, COU_SUBNAME,COU_SCORE) VALUES(COU_SEQ.NEXTVAL, '과학', 4.0);
INSERT INTO COURSE_TBL(COU_NO, COU_SUBNAME,COU_SCORE) VALUES(COU_SEQ.NEXTVAL, '국어', 5.5);

INSERT INTO ENROLL_TBL(ENR_NO, STD_NO, COU_NO, ENR_DATE) VALUES(1, 21001, 22, '23-04-05');
INSERT INTO ENROLL_TBL(ENR_NO, STD_NO, COU_NO, ENR_DATE) VALUES(2, 21003, 23, '23-05-30');
INSERT INTO ENROLL_TBL(ENR_NO, STD_NO, COU_NO, ENR_DATE) VALUES(3, 22004, 21, '23-04-21');

DROP SEQUENCE LEC_SEQ;
CREATE SEQUENCE LEC_SEQ ORDER;

INSERT INTO LECTURE_TBL(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_CLASS) VALUES(LEC_SEQ.NEXTVAL, 1, 1, '국을 보다', 'A');
INSERT INTO LECTURE_TBL(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_CLASS) VALUES(LEC_SEQ.NEXTVAL, 3, 2, '과학을 보다', 'C');
INSERT INTO LECTURE_TBL(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_CLASS) VALUES(LEC_SEQ.NEXTVAL, 2, 1, '수학을 보다', 'A');

COMMIT;

ROLLBACK;
